// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFLI-T9Dz0jwA-A3bKe1UpldFUa0FaykA',
    appId: '1:727131222603:web:5429cb8806b23d7766d3ce',
    messagingSenderId: '727131222603',
    projectId: 'my-money-55b0a',
    authDomain: 'my-money-55b0a.firebaseapp.com',
    storageBucket: 'my-money-55b0a.firebasestorage.app',
    measurementId: 'G-93Q8QYDMGL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbuGIY4n_DLMLqAQ6J8iBr7JPLFiUk2gg',
    appId: '1:727131222603:android:3824ddd47bb9b7b766d3ce',
    messagingSenderId: '727131222603',
    projectId: 'my-money-55b0a',
    storageBucket: 'my-money-55b0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxjrpehCbe6KVi5v7-Ht2cJfaXAOuzJLI',
    appId: '1:727131222603:ios:3aa4e33cadc8ed0d66d3ce',
    messagingSenderId: '727131222603',
    projectId: 'my-money-55b0a',
    storageBucket: 'my-money-55b0a.firebasestorage.app',
    iosClientId: '727131222603-7fu1hh55pg1jm26tg3a0v9ek2947r819.apps.googleusercontent.com',
    iosBundleId: 'com.example.myMoney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxjrpehCbe6KVi5v7-Ht2cJfaXAOuzJLI',
    appId: '1:727131222603:ios:3aa4e33cadc8ed0d66d3ce',
    messagingSenderId: '727131222603',
    projectId: 'my-money-55b0a',
    storageBucket: 'my-money-55b0a.firebasestorage.app',
    iosClientId: '727131222603-7fu1hh55pg1jm26tg3a0v9ek2947r819.apps.googleusercontent.com',
    iosBundleId: 'com.example.myMoney',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFLI-T9Dz0jwA-A3bKe1UpldFUa0FaykA',
    appId: '1:727131222603:web:cd89627233bf3a7866d3ce',
    messagingSenderId: '727131222603',
    projectId: 'my-money-55b0a',
    authDomain: 'my-money-55b0a.firebaseapp.com',
    storageBucket: 'my-money-55b0a.firebasestorage.app',
    measurementId: 'G-YYW9FMW0B5',
  );
}
